package main

import (
	"log"
	"net/http"
	"os"

	"github.com/joho/godotenv"
	"github.com/kuloud/tweetgo/pkg/handler"

	_ "github.com/kuloud/tweetgo/docs" // docs is generated by Swag CLI, you have to import it.
)

func init() {
	// Load .env file
	if err := godotenv.Load(); err != nil {
		log.Print("No .env file found")
	}
}

// @title X Scraper API
// @version 1.0
// @description API for scraping X profiles and tweets
// @BasePath /
func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	h := handler.NewHandler()
	log.Printf("Server starting on port %s", port)
	if err := http.ListenAndServe(":"+port, h); err != nil {
		log.Fatalf("Server failed to start: %v", err)
	}
}
