basePath: /
definitions:
  models.GIF:
    properties:
      ID:
        type: string
      Preview:
        type: string
      URL:
        type: string
    type: object
  models.Mention:
    properties:
      ID:
        type: string
      Name:
        type: string
      Username:
        type: string
    type: object
  models.Photo:
    properties:
      ID:
        type: string
      URL:
        type: string
    type: object
  models.Place:
    properties:
      bounding_box:
        properties:
          coordinates:
            items:
              items:
                items:
                  type: number
                type: array
              type: array
            type: array
          type:
            type: string
        type: object
      country:
        type: string
      country_code:
        type: string
      full_name:
        type: string
      id:
        type: string
      name:
        type: string
      place_type:
        type: string
    type: object
  models.Profile:
    properties:
      Avatar:
        type: string
      Banner:
        type: string
      Biography:
        type: string
      Birthday:
        type: string
      CanHighlightTweets:
        type: boolean
      FastFollowersCount:
        type: integer
      FollowedBy:
        type: boolean
      FollowersCount:
        type: integer
      Following:
        type: boolean
      FollowingCount:
        type: integer
      FriendsCount:
        type: integer
      HasGraduatedAccess:
        type: boolean
      IsBlueVerified:
        type: boolean
      IsPrivate:
        type: boolean
      IsVerified:
        type: boolean
      Joined:
        type: string
      LikesCount:
        type: integer
      ListedCount:
        type: integer
      Location:
        type: string
      MediaCount:
        type: integer
      Name:
        type: string
      NormalFollowersCount:
        type: integer
      PinnedTweetIDs:
        items:
          type: string
        type: array
      ProfileImageShape:
        type: string
      Sensitive:
        type: boolean
      TweetsCount:
        type: integer
      URL:
        type: string
      UserID:
        type: string
      Username:
        type: string
      Website:
        type: string
    type: object
  models.Tweet:
    properties:
      ConversationID:
        type: string
      GIFs:
        items:
          $ref: '#/definitions/models.GIF'
        type: array
      HTML:
        type: string
      Hashtags:
        items:
          type: string
        type: array
      ID:
        type: string
      InReplyToStatus:
        $ref: '#/definitions/models.Tweet'
      InReplyToStatusID:
        type: string
      IsPin:
        type: boolean
      IsQuoted:
        type: boolean
      IsReply:
        type: boolean
      IsRetweet:
        type: boolean
      IsSelfThread:
        type: boolean
      Likes:
        type: integer
      Mentions:
        items:
          $ref: '#/definitions/models.Mention'
        type: array
      Name:
        type: string
      PermanentURL:
        type: string
      Photos:
        items:
          $ref: '#/definitions/models.Photo'
        type: array
      Place:
        $ref: '#/definitions/models.Place'
      QuotedStatus:
        $ref: '#/definitions/models.Tweet'
      QuotedStatusID:
        type: string
      Replies:
        type: integer
      RetweetedStatus:
        $ref: '#/definitions/models.Tweet'
      RetweetedStatusID:
        type: string
      Retweets:
        type: integer
      SensitiveContent:
        type: boolean
      Text:
        type: string
      Thread:
        items:
          $ref: '#/definitions/models.Tweet'
        type: array
      TimeParsed:
        type: string
      Timestamp:
        type: integer
      URLs:
        items:
          type: string
        type: array
      UserID:
        type: string
      Username:
        type: string
      Videos:
        items:
          $ref: '#/definitions/models.Video'
        type: array
      Views:
        type: integer
    type: object
  models.Video:
    properties:
      HLSURL:
        type: string
      ID:
        type: string
      Preview:
        type: string
      URL:
        type: string
    type: object
host: tweetgo.vercel.app
info:
  contact: {}
  description: API for scraping X profiles and tweets
  title: X Scraper API
  version: "1.0"
paths:
  /api/v1/profile/{username}:
    get:
      description: Get the profile information of a X user by username
      parameters:
      - description: X username
        in: path
        name: username
        required: true
        type: string
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: Profile information
          schema:
            $ref: '#/definitions/models.Profile'
        "400":
          description: Invalid username
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get X profile
      tags:
      - X
  /api/v1/tweets/{username}:
    get:
      description: Get the latest tweets of a X user by username
      parameters:
      - description: X username
        in: path
        name: username
        required: true
        type: string
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: Latest tweets
          schema:
            items:
              items:
                $ref: '#/definitions/models.Tweet'
              type: array
            type: array
        "400":
          description: Invalid username
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get X tweets
      tags:
      - X
  /login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Authenticate a user and return a JWT token
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Returns a JWT token
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to generate token
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login to get a JWT token
      tags:
      - Auth
swagger: "2.0"
